name: Deploy to Hostinger

on:
  push:
    branches:
      - master  # The branch you are committing the new changes to

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Hostinger
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync Files to Hostinger
        run: |
          rsync -avz --delete --exclude '.git' ./ u185860992@157.173.209.3:/public_html/
        env:
          RSYNC_RSH: 'ssh -o StrictHostKeyChecking=no -p 65002'
